###03_ml_03: ML3 Clustering

This dataset includes descriptions of hypothetical samples corresponding to 23 species of gilled mushrooms in the Agaricus and Lepiota Family Mushroom drawn from The Audubon Society Field Guide to North American Mushrooms (1981).

Each species is identified as definitely edible, definitely poisonous, or of unknown edibility and not recommended. This latter class was combined with the poisonous one. The Guide clearly states that there is no simple rule for determining the credibility of a mushroom; no rule like "leaflets three, let it be'' for Poisonous Oak and Ivy.

**Complete class MushroomClassifier from given code template below.**

In [70]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /opt/anaconda3/envs/dsde/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /opt/anaconda3/envs/dsde/lib/python3.14/site-packages (from scikit-learn) (2.4.0)
Requirement already satisfied: scipy>=1.10.0 in /opt/anaconda3/envs/dsde/lib/python3.14/site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in /opt/anaconda3/envs/dsde/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/anaconda3/envs/dsde/lib/python3.14/site-packages (from scikit-learn) (3.6.0)

In [71]:
#import your other libraries here
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [72]:
df = pd.read_csv('ModifiedEdibleMushroom.csv')

# EDA

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5824 entries, 0 to 5823
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           5824 non-null   int64
 1   label                        5764 non-null   object
 2   cap-shape                    5824 non-null   object
 3   cap-surface                  5797 non-null   object
 4   bruises                      5725 non-null   object
 5   odor                         5725 non-null   object
 6   gill-attachment              5725 non-null   object
 7   gill-spacing                 5694 non-null   object
 8   gill-size                    5703 non-null   object
 9   stalk-shape                  5703 non-null   object
 10  stalk-root                   5793 non-null   object
 11  stalk-surface-above-ring     5793 non-null   object
 12  stalk-surface-below-ring     5793 non-null   object
 13  veil-type                    5762 non-null   object
 14  ring-number                  5762 non-null   object
 15  ring-type                    5762 non-null   object
 16  spore-print-color            5768 non-null   object
 17  population                   5768 non-null   object
 18  habitat                      5793 non-null   object
 19  cap-color-rate               5797 non-null   float64
 20  gill-color-rate              5703 non-null   float64
 21  veil-color-rate              5762 non-null   float64
 22  stalk-color-above-ring-rate  5793 non-null   float64
 23  stalk-color-below-ring-rate  5762 non-null   float64
dtypes: float64(5), int64(1), object(18)
memory usage: 1.1+ MB

In [74]:
df.head()

,id,label,cap-shape,cap-surface,bruises,odor,gill-attachment,gill-spacing,gill-size,stalk-shape,...,ring-number,ring-type,spore-print-color,population,habitat,cap-color-rate,gill-color-rate,veil-color-rate,stalk-color-above-ring-rate,stalk-color-below-ring-rate
0,1,p,x,s,t,p,f,c,n,e,...,o,p,k,s,u,1.0,3.0,1.0,1.0,1.0
1,2,e,x,s,t,a,f,c,b,e,...,o,p,n,n,g,2.0,3.0,1.0,1.0,1.0
2,3,e,b,s,t,l,f,c,b,e,...,o,p,n,n,m,3.0,1.0,1.0,1.0,1.0
3,4,p,x,y,t,p,f,c,n,e,...,o,p,k,s,u,3.0,1.0,1.0,1.0,1.0
4,5,e,x,s,f,n,f,w,b,t,...,o,e,n,a,g,4.0,3.0,1.0,1.0,1.0

In [75]:
pd.unique(df['label'])

array(['p', 'e', nan], dtype=object)

In [76]:
df = df[df['label'] == 'e']
df

,id,label,cap-shape,cap-surface,bruises,odor,gill-attachment,gill-spacing,gill-size,stalk-shape,...,ring-number,ring-type,spore-print-color,population,habitat,cap-color-rate,gill-color-rate,veil-color-rate,stalk-color-above-ring-rate,stalk-color-below-ring-rate
1,2,e,x,s,t,a,f,c,b,e,...,o,p,n,n,g,2.0,3.0,1.0,1.0,1.0
2,3,e,b,s,t,l,f,c,b,e,...,o,p,n,n,m,3.0,1.0,1.0,1.0,1.0
4,5,e,x,s,f,n,f,w,b,t,...,o,e,n,a,g,4.0,3.0,1.0,1.0,1.0
5,6,e,x,y,t,a,f,c,b,e,...,o,p,k,n,g,2.0,1.0,1.0,1.0,1.0
6,7,e,b,s,t,a,f,c,b,e,...,o,p,k,n,m,3.0,2.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5815,5816,e,x,s,f,n,a,c,b,e,...,o,p,o,v,l,1.0,10.0,2.0,7.0,8.0
5819,5820,e,k,s,f,n,a,c,b,e,...,o,p,b,c,l,1.0,10.0,2.0,7.0,8.0
5820,5821,e,x,s,f,n,a,c,b,e,...,o,p,b,v,l,1.0,10.0,1.0,7.0,8.0
5821,5822,e,f,s,f,n,a,c,b,e,...,o,p,b,c,l,1.0,1.0,2.0,7.0,8.0
5823,5824,e,x,s,f,n,a,c,b,e,...,o,p,o,c,l,1.0,10.0,2.0,7.0,8.0

In [77]:
rem_cols = df.columns.values
mask = ~np.isin(rem_cols, ["cap-color-rate", "stalk-color-above-ring-rate"])
# print(rem_cols[mask])
df = df.drop(rem_cols[mask], axis=1)
df.head()

   cap-color-rate  stalk-color-above-ring-rate
1             2.0                          1.0
2             3.0                          1.0
4             4.0                          1.0
5             2.0                          1.0
6             3.0                          1.0

In [82]:
df = df.fillna(df.mean())

In [83]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

In [84]:
df.iloc[:,:] = X_scaled

In [80]:
df

      cap-color-rate  stalk-color-above-ring-rate
1          -0.733956                    -0.742617
2          -0.233846                    -0.742617
4           0.266265                    -0.742617
5          -0.733956                    -0.742617
6          -0.233846                    -0.742617
...              ...                          ...
5815       -1.234066                     2.416548
5819       -1.234066                     2.416548
5820       -1.234066                     2.416548
5821       -1.234066                     2.416548
5823       -1.234066                     2.416548

[2104 rows x 2 columns]

In [ ]:
cluster = KMeans(n_clusters=5, random_state=0, n_init='auto')
res = cluster.fit(df)

KMeans(n_clusters=5, random_state=0)

In [91]:
np.max(res.cluster_centers_,axis=0)

array([2.5059661 , 2.30140606])

In [95]:
inv_res = scaler.inverse_transform(res.cluster_centers_)
print(np.round(np.min(inv_res, axis=0),2))

[-1.23 -0.74]

# Problem

Step 1. Load ‘ModifiedEdibleMushroom.csv’ data from the “Attachment” (note: this data set has been preliminarily prepared.).

Step 2. Choose edible mushrooms only.

Step 3. Only the variables below have been selected to describe the distinctive characteristics of edible mushrooms:
'cap-color-rate','stalk-color-above-ring-rate'

Step 4. Provide a proper data preprocessing as follows:
- Fill missing with mean.
- Standardize variables with Standard Scaler.

Step 5. K-means clustering with 5 clusters (n_clusters=5, random_state=0, n_init='auto').

Step 6. Show the maximum centroid of 2 features ('cap-color-rate' and 'stalk-color-above-ring-rate') in 2 digits.

Step 7. Convert the centroid value to the original scale, and show the minimum centroid of 2 features in 2 digits.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

class Clustering:
    def __init__(self, file_path): # DO NOT modify this line
        # Add other parameters if needed
        self.file_path = file_path 
        self.df = None #parameter for loading csv

    def Q1(self): # DO NOT modify this line
        """
        Step1-4
            1. Load the CSV file.
            2. Choose edible mushrooms only.
            3. Only the variables below have been selected to describe the distinctive
               characteristics of edible mushrooms:
               'cap-color-rate','stalk-color-above-ring-rate'
            4. Provide a proper data preprocessing as follows:
                - Fill missing with mean
                - Standardize variables with Standard Scaler
        """
        self.df = pd.read_csv(self.file_path)
        self.df = self.df[self.df["label"] == 'e']

        # drop unrelated columns
        rem_cols = self.df.columns.values
        mask = ~np.isin(rem_cols, ["cap-color-rate", "stalk-color-above-ring-rate"])
        self.df = self.df.drop(rem_cols[mask], axis=1)

        # fill missing with mean
        self.df = self.df.fillna(self.df.mean(numeric_only=True))

        # Standardize value
        scaler = StandardScaler()
        self.df.iloc[:,:] = scaler.fit_transform(self.df.iloc[:,:])

        return self.df.shape

    def Q2(self): # DO NOT modify this line
        """
        Step5-6
            5. K-means clustering with 5 clusters (n_clusters=5, random_state=0, n_init='auto')
            6. Show the maximum centroid of 2 features ('cap-color-rate' and 'stalk-color-above-ring-rate') in 2 digits.
        """
        self.df = pd.read_csv(self.file_path)
        self.df = self.df[self.df["label"] == "e"]

        # drop unrelated columns
        rem_cols = self.df.columns.values
        mask = ~np.isin(rem_cols, ["cap-color-rate", "stalk-color-above-ring-rate"])
        self.df = self.df.drop(rem_cols[mask], axis=1)

        # fill missing with mean
        self.df = self.df.fillna(self.df.mean(numeric_only=True))

        # Standardize value with StandardScaler
        scaler = StandardScaler()
        self.df.iloc[:, :] = scaler.fit_transform(self.df.iloc[:, :])

        # Clustering with K-Means
        cluster = KMeans(n_clusters=5, random_state=0, n_init='auto')
        res = cluster.fit(self.df)
        return np.round(np.max(res.cluster_centers_, axis=0),2)

    def Q3(self): # DO NOT modify this line
        """
        Step7
            7. Convert the centroid value to the original scale, and show the minimum centroid of 2 features in 2 digits.

        """
        self.df = pd.read_csv(self.file_path)
        self.df = self.df[self.df["label"] == "e"]

        # drop unrelated columns
        rem_cols = self.df.columns.values
        mask = ~np.isin(rem_cols, ["cap-color-rate", "stalk-color-above-ring-rate"])
        self.df = self.df.drop(rem_cols[mask], axis=1)

        # fill missing with mean
        self.df = self.df.fillna(self.df.mean(numeric_only=True))

        # Standardize value with StandardScaler
        scaler = StandardScaler()
        self.df.iloc[:, :] = scaler.fit_transform(self.df.iloc[:, :])

        # Clustering with K-Means
        cluster = KMeans(n_clusters=5, random_state=0, n_init="auto")
        res = cluster.fit(self.df)
        # inverse tranform to original data
        inv_res = scaler.inverse_transform(res.cluster_centers_)
        return np.round(np.min(inv_res, axis=0),2)

**Run the code below to only test that your code can work, and there is no need to submit it to the grader.**

In [109]:
def main():
    hw = Clustering('ModifiedEdibleMushroom.csv')

    # Get the input command from the user
    input_string = input().strip()
    
    # Dynamically call the method on the hw object and print the result
    input_command = f"hw.{input_string}()"
    print(f"{eval(input_command)}")

if __name__ == "__main__":
    main()

[1.01 1.  ]