In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
df = pd.read_csv('videos.csv')

In [3]:
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...

In [5]:
(df['dislikes'] > df['likes']).sum()

np.int64(576)

In [19]:
((df['trending_date'] == '18.22.01') & (df['comment_count'] > 10000)).sum()

np.int64(28)

# Q4

In [52]:
df_trend = df[['trending_date','comment_count']].copy()
df_trend['vdo_count'] = 1

In [54]:
df_trend = df_trend.groupby(['trending_date']).sum()

In [63]:
df_trend['avg'] = df_trend['comment_count'].astype(int) / df_trend['vdo_count'].astype(int)

In [65]:
df_trend['avg'].min()

np.float64(1965.3869346733668)

In [66]:
df_trend.loc[df_trend['avg'] == df_trend['avg'].min()]

               comment_count  vdo_count          avg
trending_date
18.05.02              391112        199  1965.386935

In [67]:
dfj = pd.read_json('category_id.json')

In [88]:
for e in dfj['items'].values:
    if e['snippet']['title'] == 'Sports' or e['snippet']['title'] == 'Comedy':
        print(e['snippet']['title'], ':',e['id'])

Sports : 17
Comedy : 23
Comedy : 34

In [89]:
df['category_id'].replace(34,23)

0        22
1        24
2        23
3        24
4        24
         ..
40944    15
40945    22
40946    24
40947     1
40948    20
Name: category_id, Length: 40949, dtype: int64

In [105]:
df_cat = df[['trending_date','category_id', 'views']]

In [106]:
df_cat = df_cat[(df_cat['category_id'] ==17) | (df_cat['category_id'] == 23)]

In [107]:
df_cat = df_cat.groupby(['trending_date','category_id']).sum()

In [112]:
df_cat = df_cat.reset_index()

In [119]:
df_cat_sport = df_cat[df_cat['category_id'] == 17].drop(labels=['category_id'], axis=1)
df_cat_com = df_cat[df_cat['category_id'] == 23].drop(labels=['category_id'], axis=1)

In [122]:
df_cat_sport['views']

0       4947643
2       4802877
4       5093234
6       2812344
8       2576643
         ...
400    31745208
402    36885940
404    13811205
406    39866555
408    23835174
Name: views, Length: 205, dtype: int64

In [123]:
(df_cat_sport['views'].values > df_cat_com['views'].values).sum()

np.int64(83)

## Another Sol for Q5

In [129]:
df_wide = df_cat.pivot(index='trending_date', columns='category_id', values='views')
df_wide.reset_index()

category_id trending_date        17        23
0                17.01.12   4947643  29459704
1                17.02.12   4802877  24083012
2                17.03.12   5093234  16837274
3                17.04.12   2812344  20043612
4                17.05.12   2576643  18387739
..                    ...       ...       ...
200              18.30.04  31745208  26772261
201              18.30.05  36885940  36164679
202              18.31.01  13811205  16354380
203              18.31.03  39866555  34406584
204              18.31.05  23835174  39433419

[205 rows x 3 columns]